"""Campaign content generator — OpenAI with mock fallback.

All public functions return structured dicts so the rest of the app
can treat them uniformly regardless of whether OpenAI is connected.
"""

import os
from collections import defaultdict

from src.prompts import (
    blog_outline_prompt,
    blog_draft_prompt,
    newsletter_prompt,
    linkedin_post_prompt,
)

# ── OpenAI helper (optional) ─────────────────────────────────

try:
    from openai import OpenAI
except ImportError:
    OpenAI = None


def _call_openai(prompt: str) -> str | None:
    """Send a prompt to OpenAI. Returns None when not configured."""
    api_key = os.getenv("OPENAI_API_KEY")
    if not api_key or OpenAI is None:
        return None
    # TODO: tune model, temperature, max_tokens per use-case
    client = OpenAI(api_key=api_key)
    resp = client.chat.completions.create(
        model="gpt-4o-mini",
        messages=[{"role": "user", "content": prompt}],
        max_tokens=1024,
    )
    return resp.choices[0].message.content


# ── 1. Blog outline ──────────────────────────────────────────

def generate_blog_outline(thesis: str) -> dict:
    """Return {"thesis": ..., "outline": ...}."""
    result = _call_openai(blog_outline_prompt(thesis))
    outline = result or (
        f"1. Introduction — Why \"{thesis}\" matters now\n"
        f"2. The Problem — Current challenges in this space\n"
        f"3. The Opportunity — How AI changes the equation\n"
        f"4. Key Strategies — Practical steps to get started\n"
        f"5. Common Pitfalls — Mistakes to avoid\n"
        f"6. Conclusion — Next steps and call-to-action"
    )
    return {"thesis": thesis, "outline": outline}


# ── 2. Blog draft ────────────────────────────────────────────

def generate_blog_draft(thesis: str, outline: str) -> dict:
    """Return {"thesis": ..., "outline": ..., "draft": ...}."""
    result = _call_openai(blog_draft_prompt(thesis, outline))
    draft = result or (
        f"# {thesis}\n\n"
        f"This is a mock blog draft about \"{thesis}\". In production "
        "this would be a 400–600 word article generated by OpenAI.\n\n"
        "## Key Takeaways\n"
        "- Insight one about the topic\n"
        "- Actionable advice readers can use today\n"
        "- How to measure results\n\n"
        "*[Mock content — set OPENAI_API_KEY for real generation]*"
    )
    return {"thesis": thesis, "outline": outline, "draft": draft}


# ── 3. Newsletter versions (grouped by category) ─────────────

_MOCK_HOOKS = {
    "established_prospects": "Ready to scale? Here's how leading agencies are using AI to do more with less.",
    "emerging_clients": "Getting started with AI marketing doesn't have to be overwhelming. Here's a simple playbook.",
    "general_audience": "AI is reshaping B2B marketing. Here's what you need to know this week.",
}


def generate_newsletter_versions(
    thesis: str,
    clients: list[dict],
    cta: str = "",
    tone_notes: str = "",
) -> dict:
    """Generate one newsletter per client category.

    Returns:
        {
          "thesis": str,
          "versions": [
            {"category": str, "clients": [...], "subject": str, "body": str},
            ...
          ]
        }
    """
    # Group clients by category
    by_cat: dict[str, list[dict]] = defaultdict(list)
    for c in clients:
        by_cat[c.get("category", "general_audience")].append(c)

    versions = []
    for category, cat_clients in by_cat.items():
        # Aggregate needs for the prompt
        needs_sample = ", ".join(
            c.get("needs", "") for c in cat_clients[:3] if c.get("needs")
        )
        result = _call_openai(
            newsletter_prompt(thesis, category, needs_sample, cta, tone_notes)
        )
        if result:
            # Try to split "Subject: ..." from body
            subject, body = _parse_newsletter(result)
        else:
            hook = _MOCK_HOOKS.get(category, _MOCK_HOOKS["general_audience"])
            subject = f"How \"{thesis}\" applies to {category.replace('_', ' ')}"
            body = (
                f"{hook}\n\n"
                f"*[Mock newsletter for {category.replace('_', ' ')}]*\n\n"
                f"{cta or 'Learn more →'}"
            )

        versions.append({
            "category": category,
            "clients": [c["id"] for c in cat_clients],
            "subject": subject,
            "body": body,
        })

    return {"thesis": thesis, "versions": versions}


def _parse_newsletter(text: str) -> tuple[str, str]:
    """Split an AI-generated newsletter into (subject, body)."""
    lines = text.strip().split("\n", 1)
    if lines[0].lower().startswith("subject:"):
        subject = lines[0].split(":", 1)[1].strip()
        body = lines[1].strip() if len(lines) > 1 else ""
    else:
        subject = lines[0].strip()
        body = text.strip()
    return subject, body


# ── 4. LinkedIn post ──────────────────────────────────────────

def generate_linkedin_post(thesis: str, tone_notes: str = "") -> dict:
    """Return {"thesis": ..., "post": ...}."""
    # Use general_audience tone; tone_notes override via prompt
    prompt = linkedin_post_prompt(thesis, "general_audience")
    if tone_notes:
        prompt += f"\nAdditional tone notes: {tone_notes}"
    result = _call_openai(prompt)
    post = result or (
        f"AI is reshaping how we think about \"{thesis}\".\n\n"
        "Most teams overcomplicate this. Here's a simpler way to start:\n"
        "→ Pick one workflow to automate\n"
        "→ Measure before and after\n"
        "→ Share what you learn\n\n"
        "What's the first thing you'd automate?\n\n"
        "#AI #B2B #Marketing #ContentStrategy"
    )
    return {"thesis": thesis, "post": post}


# ── 5. Full campaign content (orchestrator) ──────────────────

def generate_full_campaign_content(
    thesis: str,
    clients: list[dict],
    cta: str = "",
    tone_notes: str = "",
) -> dict:
    """Generate all content pieces for a campaign in one call.

    Returns:
        {
          "thesis": str,
          "blog_outline": str,
          "blog_draft": str,
          "newsletter_versions": [ {category, clients, subject, body}, ... ],
          "linkedin_post": str,
          "edited": False,
          "approved": False,
        }
    """
    outline_result = generate_blog_outline(thesis)
    outline = outline_result["outline"]

    draft_result = generate_blog_draft(thesis, outline)
    draft = draft_result["draft"]

    newsletters = generate_newsletter_versions(thesis, clients, cta, tone_notes)

    linkedin = generate_linkedin_post(thesis, tone_notes)

    return {
        "thesis": thesis,
        "blog_outline": outline,
        "blog_draft": draft,
        "newsletter_versions": newsletters["versions"],
        "linkedin_post": linkedin["post"],
        "edited": False,
        "approved": False,
    }
