"""Campaign content generator — OpenAI with mock fallback.

All public functions return structured dicts so the rest of the app
can treat them uniformly regardless of whether OpenAI is connected.
"""

import os
from collections import defaultdict

from src.prompts import (
    blog_outline_prompt,
    blog_draft_prompt,
    newsletter_prompt,
    linkedin_post_prompt,
)

# ── OpenAI helper (optional) ─────────────────────────────────

try:
    from openai import OpenAI
except ImportError:
    OpenAI = None


def _call_openai(prompt: str) -> str | None:
    """Send a prompt to OpenAI. Returns None when not configured."""
    api_key = os.getenv("OPENAI_API_KEY")
    if not api_key or OpenAI is None:
        return None
    # TODO: tune model, temperature, max_tokens per use-case
    client = OpenAI(api_key=api_key)
    resp = client.chat.completions.create(
        model="gpt-4o-mini",
        messages=[{"role": "user", "content": prompt}],
        max_tokens=1024,
    )
    return resp.choices[0].message.content


# ── 1. Blog outline ──────────────────────────────────────────

def generate_blog_outline(thesis: str) -> dict:
    """Return {"thesis": ..., "outline": ...}."""
    result = _call_openai(blog_outline_prompt(thesis))
    outline = result or (
        f"1. Introduction — Why \"{thesis}\" matters now\n"
        f"2. The Problem — Current challenges in this space\n"
        f"3. The Opportunity — How AI changes the equation\n"
        f"4. Key Strategies — Practical steps to get started\n"
        f"5. Common Pitfalls — Mistakes to avoid\n"
        f"6. Conclusion — Next steps and call-to-action"
    )
    return {"thesis": thesis, "outline": outline}


# ── 2. Blog draft ────────────────────────────────────────────

def generate_blog_draft(thesis: str, outline: str) -> dict:
    """Return {"thesis": ..., "outline": ..., "draft": ...}."""
    result = _call_openai(blog_draft_prompt(thesis, outline))
    draft = result or (
        f"# {thesis}\n\n"
        f"This is a mock blog draft about \"{thesis}\". In production "
        "this would be a 400–600 word article generated by OpenAI.\n\n"
        "## Key Takeaways\n"
        "- Insight one about the topic\n"
        "- Actionable advice readers can use today\n"
        "- How to measure results"
    )
    return {"thesis": thesis, "outline": outline, "draft": draft}


# ── 3. Newsletter versions (grouped by category) ─────────────

_MOCK_HOOKS = {
    "established_prospects": "Ready to scale? Here's how leading agencies are using AI to do more with less.",
    "emerging_clients": "Getting started with AI marketing doesn't have to be overwhelming. Here's a simple playbook.",
    "general_audience": "AI is reshaping B2B marketing. Here's what you need to know this week.",
}


def generate_newsletter_versions(
    thesis: str,
    clients: list[dict],
    cta: str = "",
    tone_notes: str = "",
) -> dict:
    """Generate one newsletter per client category.

    Returns:
        {
          "thesis": str,
          "versions": [
            {"category": str, "clients": [...], "subject": str, "body": str},
            ...
          ]
        }
    """
    # Group clients by category
    by_cat: dict[str, list[dict]] = defaultdict(list)
    for c in clients:
        by_cat[c.get("category", "general_audience")].append(c)

    versions = []
    for category, cat_clients in by_cat.items():
        # Aggregate needs for the prompt
        needs_sample = ", ".join(
            c.get("needs", "") for c in cat_clients[:3] if c.get("needs")
        )
        result = _call_openai(
            newsletter_prompt(thesis, category, needs_sample, cta, tone_notes)
        )
        if result:
            # Try to split "Subject: ..." from body
            subject, body = _parse_newsletter(result)
        else:
            hook = _MOCK_HOOKS.get(category, _MOCK_HOOKS["general_audience"])
            subject = f"How \"{thesis}\" applies to {category.replace('_', ' ')}"
            body = (
                f"{hook}\n\n"
                f"*[Mock newsletter for {category.replace('_', ' ')}]*\n\n"
                f"{cta or 'Learn more →'}"
            )

        versions.append({
            "category": category,
            "clients": [c["id"] for c in cat_clients],
            "subject": subject,
            "body": body,
        })

    return {"thesis": thesis, "versions": versions}


def _parse_newsletter(text: str) -> tuple[str, str]:
    """Split an AI-generated newsletter into (subject, body)."""
    lines = text.strip().split("\n", 1)
    if lines[0].lower().startswith("subject:"):
        subject = lines[0].split(":", 1)[1].strip()
        body = lines[1].strip() if len(lines) > 1 else ""
    else:
        subject = lines[0].strip()
        body = text.strip()
    return subject, body


# ── 3b. Newsletter outlines (segment-based) ──────────────────

def generate_newsletter_outlines(
    thesis: str,
    segments: list[str],
    cta: str = "",
    tone_notes: str = "",
) -> list[dict]:
    """Generate brief newsletter outlines for a list of audience segments.

    Returns:
        [{"segment": str, "subject": str, "outline": str}, ...]
    """
    outlines = []
    for segment in segments:
        prompt = (
            "You are a B2B marketing strategist at an AI startup.\n"
            f'Campaign thesis: "{thesis}"\n'
            f"Target segment: {segment}\n"
        )
        if tone_notes:
            prompt += f"Tone: {tone_notes}\n"
        if cta:
            prompt += f"CTA: {cta}\n"
        prompt += (
            "\nWrite a brief newsletter outline for this segment.\n"
            "Format:\n"
            "Subject: [one compelling subject line]\n"
            "- Key point 1\n"
            "- Key point 2\n"
            "- Key point 3\n"
        )
        result = _call_openai(prompt)
        if result:
            lines = result.strip().split("\n", 1)
            if lines[0].lower().startswith("subject:"):
                subject = lines[0].split(":", 1)[1].strip()
                outline_text = lines[1].strip() if len(lines) > 1 else ""
            else:
                subject = f'How "{thesis}" matters for {segment}'
                outline_text = result.strip()
        else:
            subject = f'How "{thesis}" matters for {segment}'
            outline_text = (
                f"- Why {segment.lower()} should pay attention to this topic\n"
                f"- Key insights and actionable takeaways for {segment.lower()}\n"
                f"- Clear next steps and call-to-action"
            )
        outlines.append(
            {"segment": segment, "subject": subject, "outline": outline_text}
        )
    return outlines


# ── 3c. Persona-based newsletter options (3 per persona) ─────

def generate_persona_newsletters(
    thesis: str,
    persona: dict,
    cta: str = "",
    tone_notes: str = "",
    layout: str = "",
    count: int = 3,
) -> list[dict]:
    """Generate *count* distinct newsletter drafts for one persona.

    Returns list of {"segment", "subject", "body", "angle"} dicts.
    """
    from src.personas import PERSONAS  # local import to avoid circular

    angles = [
        "Challenge-first: lead with the pain point, then offer the solution",
        "Story-driven: open with a brief anecdote or case example",
        "Data-driven: lead with a compelling statistic or trend",
    ]
    title = persona["title"]
    pain_points = persona.get("pain_points", [])
    messaging_angle = persona.get("messaging_angle", "")

    results: list[dict] = []
    for i in range(min(count, len(angles))):
        angle = angles[i]
        prompt = (
            "You are a B2B marketing content writer at an AI startup.\n"
            f'Campaign thesis: "{thesis}"\n'
            f"Target persona: {title}\n"
            f"Persona pain points: {', '.join(pain_points)}\n"
            f"Messaging angle: {messaging_angle}\n"
            f"Writing approach: {angle}\n"
        )
        if cta:
            prompt += f"CTA: {cta}\n"
        if tone_notes:
            prompt += f"Tone: {tone_notes}\n"
        if layout:
            prompt += f"Layout style: {layout}\n"
        prompt += (
            "\nWrite a complete newsletter email (200-350 words).\n"
            "Start with 'Subject: [subject line]' on its own line.\n"
            "Then write the full email body with a greeting, content, and CTA."
        )
        result = _call_openai(prompt)
        if result:
            subject, body = _parse_newsletter(result)
        else:
            pain = pain_points[i % len(pain_points)] if pain_points else "key challenges"
            if i == 0:
                subject = f'How "{thesis}" solves {pain.lower()}'
                body = (
                    f"Hi there,\n\n"
                    f"As a {title.lower()}, you know the struggle: **{pain.lower()}**.\n\n"
                    f'That\'s exactly why "{thesis}" matters. '
                    f"Here's what's changing:\n\n"
                    f"**The Challenge**\n"
                    f"Most teams are still stuck in manual processes that don't scale.\n\n"
                    f"**The Solution**\n"
                    f"- Automate repetitive workflows\n"
                    f"- Focus your team on high-value work\n"
                    f"- Measure and iterate faster\n\n"
                    f"{cta or 'Book a demo →'}"
                )
            elif i == 1:
                subject = f'A {title.lower()} transformed their team — here\'s how'
                body = (
                    f"Hi there,\n\n"
                    f"Last quarter, a {title.lower()} just like you transformed "
                    f"their team's output by rethinking how they approach "
                    f"{pain.lower()}.\n\n"
                    f'Here\'s what we learned about "{thesis}":\n\n'
                    f"**The Story**\n"
                    f"They started small — one workflow, one tool, one month.\n\n"
                    f"**The Results**\n"
                    f"- 40% time saved on routine tasks\n"
                    f"- Better team satisfaction scores\n"
                    f"- Tangible ROI within 60 days\n\n"
                    f"{cta or 'See the full case study →'}"
                )
            else:
                subject = f'78% of {title.lower()}s say this is their #1 challenge'
                body = (
                    f"Hi there,\n\n"
                    f"**78% of {title.lower()}s** say {pain.lower()} is their "
                    f"#1 challenge this year.\n\n"
                    f'Our research on "{thesis}" reveals three key trends:\n\n'
                    f"**By the Numbers**\n"
                    f"- Teams using AI workflows save 12+ hours/week\n"
                    f"- Early adopters see 3x engagement rates\n"
                    f"- 65% plan to increase investment next quarter\n\n"
                    f"**What This Means for You**\n"
                    f"The window to gain a competitive edge is closing. "
                    f"Don't get left behind.\n\n"
                    f"{cta or 'Get the full report →'}"
                )
        results.append({
            "segment": title,
            "subject": subject,
            "body": body,
            "angle": angle,
        })
    return results


# ── 3d. Full newsletter for one segment ──────────────────────

def generate_newsletter_full(
    thesis: str,
    segment: str,
    cta: str = "",
    tone_notes: str = "",
    layout: str = "",
) -> dict:
    """Generate a complete newsletter email for one audience segment.

    Returns:
        {"segment": str, "subject": str, "body": str}
    """
    prompt = (
        "You are a B2B marketing content writer at an AI startup.\n"
        f'Campaign thesis: "{thesis}"\n'
        f"Target segment: {segment}\n"
    )
    if cta:
        prompt += f"CTA: {cta}\n"
    if tone_notes:
        prompt += f"Tone: {tone_notes}\n"
    if layout:
        prompt += f"Layout style: {layout}. Structure the email accordingly.\n"
    prompt += (
        "\nWrite a complete newsletter email (200-350 words).\n"
        "Start with 'Subject: [subject line]' on its own line.\n"
        "Then write the full email body with a greeting, content, and CTA."
    )
    result = _call_openai(prompt)
    if result:
        subject, body = _parse_newsletter(result)
    else:
        subject = f'How "{thesis}" applies to {segment}'
        body = (
            f"Hi there,\n\n"
            f"As part of our {segment.lower()} community, we wanted to share "
            f'key insights about "{thesis}".\n\n'
            f"**Why This Matters**\n"
            f"This topic is reshaping how teams work and creating new "
            f"opportunities for growth.\n\n"
            f"**What You Can Do**\n"
            f"- Review your current approach\n"
            f"- Identify one area for improvement\n"
            f"- Start with a small, measurable pilot\n\n"
            f"**Next Steps**\n"
            f"{cta or 'Learn more at novamind.ai →'}"
        )
    return {"segment": segment, "subject": subject, "body": body}


# ── 4. LinkedIn post ──────────────────────────────────────────

def generate_linkedin_post(thesis: str, tone_notes: str = "") -> dict:
    """Return {"thesis": ..., "post": ...}."""
    # Use general_audience tone; tone_notes override via prompt
    prompt = linkedin_post_prompt(thesis, "general_audience")
    if tone_notes:
        prompt += f"\nAdditional tone notes: {tone_notes}"
    result = _call_openai(prompt)
    post = result or (
        f"AI is reshaping how we think about \"{thesis}\".\n\n"
        "Most teams overcomplicate this. Here's a simpler way to start:\n"
        "→ Pick one workflow to automate\n"
        "→ Measure before and after\n"
        "→ Share what you learn\n\n"
        "What's the first thing you'd automate?\n\n"
        "#AI #B2B #Marketing #ContentStrategy"
    )
    return {"thesis": thesis, "post": post}


# ── 5. Thesis suggestion ─────────────────────────────────────

def suggest_thesis(raw_thesis: str) -> str:
    """Suggest a more prompt-friendly version of the user's thesis."""
    prompt = (
        "You are a B2B marketing strategist. "
        "Rewrite the following campaign thesis so it is clearer, "
        "more specific, and better suited for AI content generation. "
        "Return only the improved thesis, nothing else.\n\n"
        f"Original: {raw_thesis}"
    )
    result = _call_openai(prompt)
    if result:
        return result.strip().strip('"')
    # Rule-based fallback
    cleaned = raw_thesis.strip().rstrip(".")
    return f"How {cleaned.lower()} — and why it matters for B2B teams today"


# ── 6. Full campaign content (orchestrator) ──────────────────

def generate_full_campaign_content(
    thesis: str,
    clients: list[dict],
    cta: str = "",
    tone_notes: str = "",
    content_types: list[str] | None = None,
) -> dict:
    """Generate selected content pieces for a campaign.

    content_types controls what gets generated. Defaults to ["Blog", "Newsletter"].

    Returns:
        {
          "thesis": str,
          "blog_outline": str,
          "blog_draft": str,
          "newsletter_versions": [ {category, clients, subject, body}, ... ],
          "edited": False,
          "approved": False,
        }
    """
    if content_types is None:
        content_types = ["Blog", "Newsletter"]

    outline = ""
    draft = ""
    newsletter_versions: list[dict] = []

    if "Blog" in content_types:
        outline_result = generate_blog_outline(thesis)
        outline = outline_result["outline"]
        draft_result = generate_blog_draft(thesis, outline)
        draft = draft_result["draft"]

    if "Newsletter" in content_types:
        newsletters = generate_newsletter_versions(thesis, clients, cta, tone_notes)
        newsletter_versions = newsletters["versions"]

    return {
        "thesis": thesis,
        "blog_outline": outline,
        "blog_draft": draft,
        "newsletter_versions": newsletter_versions,
        "edited": False,
        "approved": False,
    }
