"""Content generation via OpenAI (falls back to mock data)."""

import os

from src.prompts import (
    blog_outline_prompt,
    blog_draft_prompt,
    newsletter_prompt,
    linkedin_post_prompt,
)

# Optional: only used when OPENAI_API_KEY is set
try:
    from openai import OpenAI
except ImportError:
    OpenAI = None


def _call_openai(prompt: str) -> str | None:
    """Call the OpenAI chat API. Returns None if not configured."""
    api_key = os.getenv("OPENAI_API_KEY")
    if not api_key or OpenAI is None:
        return None
    client = OpenAI(api_key=api_key)
    resp = client.chat.completions.create(
        model="gpt-4o-mini",
        messages=[{"role": "user", "content": prompt}],
        max_tokens=1024,
    )
    return resp.choices[0].message.content


# ── Public API ───────────────────────────────────────────────


def generate_blog_outline(thesis: str) -> str:
    result = _call_openai(blog_outline_prompt(thesis))
    if result:
        return result
    return (
        f"1. Introduction — Why \"{thesis}\" matters now\n"
        f"2. The Problem — Current challenges in this space\n"
        f"3. The Opportunity — How AI changes the equation\n"
        f"4. Key Strategies — Practical steps to get started\n"
        f"5. Common Pitfalls — Mistakes to avoid\n"
        f"6. Conclusion — Next steps and call-to-action"
    )


def generate_blog_draft(thesis: str, outline: str) -> str:
    result = _call_openai(blog_draft_prompt(thesis, outline))
    if result:
        return result
    return (
        f"# {thesis}\n\n"
        f"This is a mock blog draft about \"{thesis}\". "
        "In a live environment this would be a 400-600 word article "
        "generated by OpenAI following the provided outline.\n\n"
        "## Key Takeaways\n"
        "- Point one about the topic\n"
        "- Point two with actionable advice\n"
        "- Point three on measuring results\n\n"
        "*[Mock content — connect your OpenAI key for real generation]*"
    )


def generate_newsletter(thesis: str, category: str,
                         client_needs: str = "", cta: str = "",
                         tone_notes: str = "") -> str:
    """Generate a single newsletter for one category/client."""
    result = _call_openai(
        newsletter_prompt(thesis, category, client_needs, cta, tone_notes)
    )
    if result:
        return result
    return (
        f"Subject: How \"{thesis}\" applies to you\n\n"
        f"Hi — here's what {category.replace('_', ' ')} teams "
        f"need to know about this topic.\n\n"
        f"*[Mock newsletter — connect OpenAI for real generation]*\n\n"
        f"CTA: {cta or 'Learn more'}"
    )


def generate_newsletters_for_categories(
    thesis: str, categories: list[str],
    cta: str = "", tone_notes: str = "",
) -> list[dict]:
    """Generate one newsletter per category. Returns a list of dicts."""
    results = []
    for cat in categories:
        body = generate_newsletter(thesis, cat, cta=cta, tone_notes=tone_notes)
        results.append({"category": cat, "body": body})
    return results


def generate_linkedin_post(thesis: str,
                            category: str = "general_audience") -> str:
    result = _call_openai(linkedin_post_prompt(thesis, category))
    if result:
        return result
    return (
        f"AI is reshaping how we think about \"{thesis}\".\n\n"
        "Here's what most teams get wrong — and how to fix it.\n\n"
        "*[Mock LinkedIn post — connect OpenAI for real generation]*\n\n"
        "#AI #Marketing #B2B #ContentStrategy"
    )
